[build-system]
requires = [
    "setuptools>=61.0.0",  # setuptools 61.0 fully embraces 'pyproject.toml' configuration
    "setuptools-scm>=8"  # when installed it automatically includes all git-tracked files into our source distribution
]
build-backend = "setuptools.build_meta"

[project]
name = "pybacktrack"
dynamic = ["version"]
description = "A tool for reconstructing paleobathymetry on oceanic and continental crust."
readme = "README.rst"
authors = [{ name = "John Cannon", email = "john.cannon@sydney.edu.au" }]
# TODO: Uncomment these two license lines when Python 3.8 is no longer our min. requirement.
#       And also remove "License ::" from 'classifiers' (replaced by updated 'license' field).
#       This requires Python >=3.9 (setuptools >=77.0).
#       Until then we will get the warning "License classifiers are deprecated".
#
#license = "GPL-2.0-only"
#license-files = ["LICENSE"]
requires-python = ">=3.8"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]
keywords = ["bathymetry", "backtrack", "backstrip", "rift", "subsidence", "tectonic"]
dependencies = [
    "numpy",
    "scipy",
    "pygplates",
    # Support for accessing *namespace* packages only added in Python 3.10 (to 'importlib.resources').
    # For Python <3.10 must instead use backport PyPI package 'importlib_resources'.
    "importlib_resources;python_version<'3.10'",
    "packaging>=20.0",  # For version parsing and comparison (used by 'pybacktrack.version' module).
]
urls.Homepage = "https://github.com/EarthByte/pyBacktrack"
urls.Documentation = "http://pybacktrack.readthedocs.io"
optional-dependencies.dev = [
    # Used by supplementary script 'generate_rift_grids.py'.
    # Alternatively can use "PlateTectonicTools" (which is no longer developed, and now contained within "gplately").
    "gplately",
    "pytest",
    "Sphinx>=1.8",
    "sphinx-rtd-theme"
]

[tool.setuptools]
# Help setuptools to look only at the 'pybacktrack' package (so doesn't think other top-level dirs are packages).
packages.find.include = ["pybacktrack*"]
# Ensure embedded *data* folders are found (they look like namespace packages, ie, no '__init__.py' in folder).
packages.find.namespaces = true
# Include package data in the *wheel*.
#
# "setuptools-scm" and 'MANIFEST.in' determine what data files go in the *sdist*.
# And "include-package-data=true" also includes them in the *wheel*,
# but only those *inside* the package directory tree ('pybacktrack*') by default.
#
# Note: "setuptools-scm" restricts to git-tracked files.
#       'MANIFEST.in' excludes some git-tracked files included by "setuptools-scm".
include-package-data = true

[tool.setuptools_scm]
# This section must be present (even if empty) for setuptools-scm <8.1.

[tool.setuptools_scm.scm.git]
# Attempt to fetch enough history to find a git version tag.
# This is needed for Readthedocs builds, which use a shallow clone of the repository (ie, no tags).
pre_parse = "fetch_on_shallow"

[tool.pytest.ini_options]
testpaths = ["tests"]
