{% set name = "pybacktrack" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - gmt >=5.0.0
    - numpy
    - pygplates
    - scipy

test:
  source_files:
    - tests
  imports:
    - pybacktrack
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - py

about:
  home: https://github.com/EarthByte/pyBacktrack
  summary: A tool for reconstructing paleobathymetry on oceanic and continental crust.
  dev_url: https://github.com/EarthByte/pyBacktrack
  doc_url: https://pybacktrack.readthedocs.io
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcannon-gplates
