{% set name = "pybacktrack" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8b540d2839062ba4964b6635177e376b649ba360720040f1b519afd7f0cab1d3

build:
  noarch: python
  script_env:
    # There's no '.git' directory in source tarball, so explicitly provide version for setuptools_scm.
    - SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYBACKTRACK={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    # Using same setuptools[_scm] versions as pyproject.toml (in source tarball).
    - setuptools >=61.0
    - setuptools_scm >=8.0  # Need this to process SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYBACKTRACK env var.
  run:
    - python >={{ python_min }}
    - gmt >=5.0
    - numpy
    - pygplates
    - scipy
    - packaging >=20.0  # Dependency in pyproject.toml (to parse versions in pybacktrack).

test:
  source_files:
    - tests
  imports:
    - pybacktrack
  requires:
    - python {{ python_min }}
    - pytest
  commands:
    # Temporary: Tests only pass on Windows.
    #            Fails on Linux/macOS.
    #            GMT is reporting grdtrack error: Named variable does not exist in file (sediment thickness grid).
    #            Appears to not detect the 'z' variable in grid (even though 'ncdump -h' shows it).
    #            Likely some NetCDF/HDF5 driver issue within GMT. The same versions of GMT/libnetcdf/hdf4/hdf5 and
    #            pretty much all the libraries are the same on my local macOS machine and it works fine.
    #
    # TODO: Remove this in the next version upgrade of pyBacktrack.
    - pytest  # [win]

about:
  home: https://github.com/EarthByte/pyBacktrack
  summary: A tool for reconstructing paleobathymetry on oceanic and continental crust.
  dev_url: https://github.com/EarthByte/pyBacktrack
  doc_url: https://pybacktrack.readthedocs.io
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcannon-gplates
